/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ortiz.testingavro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Person extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1413440546383486765L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Person\",\"namespace\":\"com.ortiz.testingavro\",\"fields\":[{\"name\":\"tenantId\",\"type\":\"string\"},{\"name\":\"fullName\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Person> ENCODER =
      new BinaryMessageEncoder<Person>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Person> DECODER =
      new BinaryMessageDecoder<Person>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Person> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Person> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Person>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Person to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Person from a ByteBuffer. */
  public static Person fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence tenantId;
  @Deprecated public java.lang.CharSequence fullName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Person() {}

  /**
   * All-args constructor.
   * @param tenantId The new value for tenantId
   * @param fullName The new value for fullName
   */
  public Person(java.lang.CharSequence tenantId, java.lang.CharSequence fullName) {
    this.tenantId = tenantId;
    this.fullName = fullName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tenantId;
    case 1: return fullName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tenantId = (java.lang.CharSequence)value$; break;
    case 1: fullName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'tenantId' field.
   * @return The value of the 'tenantId' field.
   */
  public java.lang.CharSequence getTenantId() {
    return tenantId;
  }

  /**
   * Sets the value of the 'tenantId' field.
   * @param value the value to set.
   */
  public void setTenantId(java.lang.CharSequence value) {
    this.tenantId = value;
  }

  /**
   * Gets the value of the 'fullName' field.
   * @return The value of the 'fullName' field.
   */
  public java.lang.CharSequence getFullName() {
    return fullName;
  }

  /**
   * Sets the value of the 'fullName' field.
   * @param value the value to set.
   */
  public void setFullName(java.lang.CharSequence value) {
    this.fullName = value;
  }

  /**
   * Creates a new Person RecordBuilder.
   * @return A new Person RecordBuilder
   */
  public static com.ortiz.testingavro.Person.Builder newBuilder() {
    return new com.ortiz.testingavro.Person.Builder();
  }

  /**
   * Creates a new Person RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Person RecordBuilder
   */
  public static com.ortiz.testingavro.Person.Builder newBuilder(com.ortiz.testingavro.Person.Builder other) {
    return new com.ortiz.testingavro.Person.Builder(other);
  }

  /**
   * Creates a new Person RecordBuilder by copying an existing Person instance.
   * @param other The existing instance to copy.
   * @return A new Person RecordBuilder
   */
  public static com.ortiz.testingavro.Person.Builder newBuilder(com.ortiz.testingavro.Person other) {
    return new com.ortiz.testingavro.Person.Builder(other);
  }

  /**
   * RecordBuilder for Person instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Person>
    implements org.apache.avro.data.RecordBuilder<Person> {

    private java.lang.CharSequence tenantId;
    private java.lang.CharSequence fullName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ortiz.testingavro.Person.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tenantId)) {
        this.tenantId = data().deepCopy(fields()[0].schema(), other.tenantId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fullName)) {
        this.fullName = data().deepCopy(fields()[1].schema(), other.fullName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Person instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ortiz.testingavro.Person other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.tenantId)) {
        this.tenantId = data().deepCopy(fields()[0].schema(), other.tenantId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fullName)) {
        this.fullName = data().deepCopy(fields()[1].schema(), other.fullName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'tenantId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTenantId() {
      return tenantId;
    }

    /**
      * Sets the value of the 'tenantId' field.
      * @param value The value of 'tenantId'.
      * @return This builder.
      */
    public com.ortiz.testingavro.Person.Builder setTenantId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tenantId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tenantId' field has been set.
      * @return True if the 'tenantId' field has been set, false otherwise.
      */
    public boolean hasTenantId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tenantId' field.
      * @return This builder.
      */
    public com.ortiz.testingavro.Person.Builder clearTenantId() {
      tenantId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'fullName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFullName() {
      return fullName;
    }

    /**
      * Sets the value of the 'fullName' field.
      * @param value The value of 'fullName'.
      * @return This builder.
      */
    public com.ortiz.testingavro.Person.Builder setFullName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.fullName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'fullName' field has been set.
      * @return True if the 'fullName' field has been set, false otherwise.
      */
    public boolean hasFullName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'fullName' field.
      * @return This builder.
      */
    public com.ortiz.testingavro.Person.Builder clearFullName() {
      fullName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Person build() {
      try {
        Person record = new Person();
        record.tenantId = fieldSetFlags()[0] ? this.tenantId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.fullName = fieldSetFlags()[1] ? this.fullName : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Person>
    WRITER$ = (org.apache.avro.io.DatumWriter<Person>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Person>
    READER$ = (org.apache.avro.io.DatumReader<Person>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
